[package]
name = "rsmqttd"
version = "0.2.0"
edition = "2018"
license = "GPL-3.0"

[dependencies]
codec = { path = "../../libs/codec", package = "rsmqttd-codec" }

anyhow = "1.0.41"
tokio = { version = "1.7.1", features = ["sync", "rt-multi-thread", "time", "macros", "net", "io-util"] }
tracing = "0.1.26"
tokio-stream = "0.1.6"
bytestring = "1.0.0"
toml = "0.5.8"
serde = { version = "1.0.126", features = ["derive"] }
structopt = "0.3.21"
tracing-subscriber = "0.2.18"
fnv = "1.0.7"
bytes = "1.0.1"
async-trait = "0.1.50"
dirs = "3.0.2"
indexmap = "1.6.2"
uuid = { version = "0.8.2", features = ["v4"] }
thiserror = "1.0.25"
parking_lot = "0.11.1"
fastrand = "1.4.1"
tokio-rustls = "0.22.0"
warp = { version = "0.3.1", features = ["tls"] }
tokio-util = "0.6.7"
futures-util = { version = "0.3.15", features = ["sink"] }
version = "3.0.0"

